<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <!-- Revit References -->
        <PackageReference Include="Nice3point.Revit.Build.Tasks" Version="3.0.1"/>
        <PackageReference Include="Nice3point.Revit.Toolkit" Version="$(RevitVersion).*"/>
        <PackageReference Include="Nice3point.Revit.Extensions" Version="$(RevitVersion).*"/>
        <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*"/>
        <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*"/>

        <!-- MVVM -->
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0"/>

        <!-- IOC -->
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3"/>

        <!-- Build -->
        <PackageReference Include="ILRepack" Version="2.0.41"/>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Resources\Icons\RibbonIcon16.png"/>
        <Resource Include="Resources\Icons\RibbonIcon32.png"/>
    </ItemGroup>

</Project>